### ISSUE TITLE
Check readme file

### ISSUE THREAD

**Issue by cagabi** [carboncoop/geovation#1]
I have copied the content from a document I found in CarbonCoop's Dropbox project folder. If anybody has anything better or wants to change it, please let me know
https://github.com/carboncoop/geovation/blob/master/README.md

**Comment by beaylott** [comment]
It would be good to reconcile the name of the website with the URL. The sub-domain 'geovation' doesn't fit very well with the website being called 'My Home Energy Salford'.

**Comment by beaylott** [comment]
I made some edits to the README. It also should provide instructions on how to create a running instance of the site.

**Comment by beaylott** [comment]
Actually on second reading i didnt understand what this website was actually doing at all. It might be better to just create a much shorter single paragraph explanation and refer to other sites/repositories for further detail.

**Comment by cagabi** [comment]
I have changed the subdomain to myhomeenergysalford.carbon.coop. Should be available soon
