### ISSUE TITLE
Search bar in wrong place

### ISSUE THREAD

**Issue by beaylott** [carboncoop/geovation#2]
In Firefox 52 on Linux x64 at 1080p the search bar / banner are displaced upwards as can be seen in the attached image.
![search bar move up](https://cloud.githubusercontent.com/assets/654056/25174706/21b9da6a-24f0-11e7-8914-3915de061066.jpg)

**Comment by beaylott** [comment]
It doesn't do this on Chrome 57 on the same system.

**Comment by cagabi** [comment]
Fixed
